In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats
import os

DATA = "../data/processed/"
CHARTS = "../reports/eda_charts/"
os.makedirs(CHARTS, exist_ok=True)

nav_history = pd.read_csv(DATA + "nav_history_clean.csv")
fund_master = pd.read_csv(DATA + "fund_master_clean.csv")
benchmark = pd.read_csv(DATA + "benchmark_indices_clean.csv")

nav_history["date"] = pd.to_datetime(nav_history["date"])
nav_history = nav_history.sort_values(["amfi_code", "date"])

In [22]:
nav_history["daily_return"] = nav_history.groupby("amfi_code")["nav"].pct_change()

print(nav_history["daily_return"].describe())
# Validate distribution looks reasonable — most daily equity fund returns should be small, roughly -5% to +5%
print("Extreme outliers (>10% daily move):", (nav_history["daily_return"].abs() > 0.10).sum())

count    64280.000000
mean         0.000451
std          0.008706
min         -0.058102
25%         -0.002092
50%          0.000000
75%          0.003233
max          0.064713
Name: daily_return, dtype: float64
Extreme outliers (>10% daily move): 0

In [23]:
def calc_cagr(nav_start, nav_end, years):
    if nav_start <= 0 or years <= 0:
        return np.nan
    return (nav_end / nav_start) ** (1/years) - 1

cagr_results = []
latest_date = nav_history["date"].max()

for code, group in nav_history.groupby("amfi_code"):
    group = group.set_index("date")
    row = {"amfi_code": code}
    for years, label in [(1, "cagr_1yr"), (3, "cagr_3yr"), (5, "cagr_5yr")]:
        target_date = latest_date - pd.DateOffset(years=years)
        past = group[group.index <= target_date]
        if len(past) > 0 and len(group) > 0:
            nav_start = past["nav"].iloc[-1]
            nav_end = group["nav"].iloc[-1]
            actual_years = (group.index[-1] - past.index[-1]).days / 365.25
            row[label] = calc_cagr(nav_start, nav_end, actual_years)
        else:
            row[label] = np.nan
    cagr_results.append(row)

cagr_df = pd.DataFrame(cagr_results)
cagr_df = cagr_df.merge(fund_master[["amfi_code","scheme_name"]], on="amfi_code")
cagr_df

,amfi_code,cagr_1yr,cagr_3yr,cagr_5yr,scheme_name
0,100016,-0.022258,0.012924,NaN,HDFC Top 100 Fund - Regular Plan - Growth
1,100025,0.037076,0.039155,NaN,HDFC Short Term Debt Fund - Regular - Growth
2,100033,0.532772,0.324340,NaN,HDFC Mid-Cap Opportunities Fund - Regular - Gr...
3,101206,0.479638,0.289602,NaN,ABSL Frontline Equity Fund - Regular - Growth
4,101207,-0.240003,-0.041515,NaN,ABSL Small Cap Fund - Regular - Growth
5,101208,0.072418,0.063143,NaN,ABSL Liquid Fund - Regular - Growth
6,102885,0.202229,0.196624,NaN,UTI Nifty 50 Index Fund - Regular - Growth
7,102886,-0.168080,-0.007672,NaN,UTI Mid Cap Fund - Regular - Growth
8,102887,0.135930,0.255497,NaN,UTI Flexi Cap Fund - Regular - Growth
9,118632,0.340079,0.226466,NaN,Nippon India Large Cap Fund - Regular - Growth
10,118633,0.255595,0.210847,NaN,Nippon India Large Cap Fund - Direct - Growth
11,118634,0.158229,0.080060,NaN,Nippon India Small Cap Fund - Regular - Growth
12,118635,0.225102,0.200032,NaN,Nippon India ETF Nifty 50 BeES
13,118636,0.104625,0.040613,NaN,Nippon India Gilt Securities Fund - Regular - ...
14,119092,0.016102,0.005258,NaN,Axis Bluechip Fund - Regular - Growth
15,119093,0.197815,0.208116,NaN,Axis Bluechip Fund - Direct - Growth
16,119094,0.222779,0.351025,NaN,Axis Midcap Fund - Regular - Growth
17,119095,-0.428195,-0.117033,NaN,Axis Small Cap Fund - Regular - Growth
18,119120,0.055259,0.058390,NaN,SBI Magnum Gilt Fund - Regular Plan - Growth
19,119551,0.604893,0.304486,NaN,SBI Bluechip Fund - Regular Plan - Growth
20,119552,0.057101,0.162634,NaN,SBI Bluechip Fund - Direct Plan - Growth
21,119598,0.828516,0.266631,NaN,SBI Small Cap Fund - Regular Plan - Growth
22,119599,0.139580,-0.013371,NaN,SBI Small Cap Fund - Direct Plan - Growth
23,120503,0.084951,0.139750,NaN,ICICI Pru Bluechip Fund - Regular - Growth
24,120504,0.130738,0.324789,NaN,ICICI Pru Bluechip Fund - Direct - Growth
25,120505,0.296277,0.317692,NaN,ICICI Pru Midcap Fund - Regular - Growth
26,120506,0.418530,0.184174,NaN,ICICI Pru Value Discovery Fund - Regular - Growth
27,120507,0.074303,0.073925,NaN,ICICI Pru Liquid Fund - Regular - Growth
28,120841,0.168496,0.172630,NaN,Kotak Bluechip Fund - Regular - Growth
29,120842,0.225190,0.077542,NaN,Kotak Emerging Equity Fund - Regular - Growth
30,120843,0.266776,0.295751,NaN,Kotak Flexicap Fund - Regular - Growth
31,120844,0.071254,0.066944,NaN,Kotak Liquid Fund - Regular - Growth
32,125497,0.286976,0.184299,NaN,HDFC Top 100 Fund - Direct Plan - Growth
33,125498,0.154551,0.112425,NaN,HDFC Mid-Cap Opportunities Fund - Direct - Growth
34,148567,0.203760,0.339920,NaN,Mirae Asset Large Cap Fund - Regular - Growth
35,148568,0.142798,0.147444,NaN,Mirae Asset Emerging Bluechip Fund - Regular -...
36,148569,0.397838,0.291714,NaN,Mirae Asset Tax Saver Fund - Regular - Growth
37,149322,0.181246,0.180397,NaN,DSP Top 100 Equity Fund - Regular - Growth
38,149323,0.214974,0.268631,NaN,DSP Midcap Fund - Regular - Growth
39,149324,0.651955,0.269935,NaN,DSP Small Cap Fund - Regular - Growth

In [24]:
Rf = 0.065  # RBI repo rate proxy, annualized

sharpe_results = []
for code, group in nav_history.groupby("amfi_code"):
    returns = group["daily_return"].dropna()
    if len(returns) < 2:
        continue
    ann_return = returns.mean() * 252
    ann_std = returns.std() * np.sqrt(252)
    sharpe = (ann_return - Rf) / ann_std if ann_std > 0 else np.nan
    sharpe_results.append({"amfi_code": code, "sharpe_ratio": sharpe})

sharpe_df = pd.DataFrame(sharpe_results)
sharpe_df["rank"] = sharpe_df["sharpe_ratio"].rank(ascending=False)
sharpe_df = sharpe_df.sort_values("sharpe_ratio", ascending=False)
sharpe_df

    amfi_code  sharpe_ratio  rank
34     148567      1.068224   1.0
30     120843      0.965561   2.0
36     148569      0.919047   3.0
25     120505      0.883256   4.0
19     119551      0.860977   5.0
38     149323      0.832885   6.0
2      100033      0.808268   7.0
9      118632      0.758851   8.0
16     119094      0.730547   9.0
3      101206      0.717409  10.0
24     120504      0.714682  11.0
39     149324      0.714422  12.0
21     119598      0.711690  13.0
20     119552      0.648241  14.0
35     148568      0.640673  15.0
6      102885      0.519797  16.0
23     120503      0.516550  17.0
32     125497      0.506273  18.0
26     120506      0.404615  19.0
12     118635      0.393188  20.0
10     118633      0.388829  21.0
8      102887      0.384637  22.0
11     118634      0.292343  23.0
28     120841      0.255117  24.0
37     149322      0.239663  25.0
33     125498      0.134798  26.0
4      101207      0.052618  27.0
15     119093     -0.047073  28.0
29     120842     -0.058167  29.0
14     119092     -0.131009  30.0
22     119599     -0.136178  31.0
17     119095     -0.151658  32.0
7      102886     -0.294889  33.0
0      100016     -0.321019  34.0
18     119120     -0.743099  35.0
13     118636     -0.850579  36.0
1      100025     -1.039941  37.0
27     120507     -3.650184  38.0
31     120844     -4.000349  39.0
5      101208     -4.650401  40.0

In [25]:
sortino_results = []
for code, group in nav_history.groupby("amfi_code"):
    returns = group["daily_return"].dropna()
    if len(returns) < 2:
        continue
    ann_return = returns.mean() * 252
    downside_returns = returns[returns < 0]
    downside_std = downside_returns.std() * np.sqrt(252) if len(downside_returns) > 1 else np.nan
    sortino = (ann_return - Rf) / downside_std if downside_std and downside_std > 0 else np.nan
    sortino_results.append({"amfi_code": code, "sortino_ratio": sortino})

sortino_df = pd.DataFrame(sortino_results)
sortino_df

    amfi_code  sortino_ratio
0      100016      -0.472822
1      100025      -1.461220
2      100033       1.144216
3      101206       1.063909
4      101207       0.075668
5      101208      -8.741654
6      102885       0.772972
7      102886      -0.420589
8      102887       0.571858
9      118632       1.098880
10     118633       0.588633
11     118634       0.411304
12     118635       0.569426
13     118636      -1.238302
14     119092      -0.189188
15     119093      -0.067900
16     119094       1.055284
17     119095      -0.216346
18     119120      -1.045910
19     119551       1.291483
20     119552       0.926563
21     119598       1.067256
22     119599      -0.190035
23     120503       0.732916
24     120504       1.063964
25     120505       1.285843
26     120506       0.578136
27     120507      -7.208234
28     120841       0.376619
29     120842      -0.080696
30     120843       1.479503
31     120844      -7.768003
32     125497       0.734798
33     125498       0.192947
34     148567       1.490739
35     148568       0.955767
36     148569       1.352815
37     149322       0.332952
38     149323       1.167793
39     149324       1.030962

In [26]:
print(benchmark["index_name"].unique())

<StringArray>
[        'NIFTY50',        'NIFTY100', 'NIFTY_MIDCAP150',    'BSE_SMALLCAP',
        'NIFTY500',   'CRISIL_LIQUID',     'CRISIL_GILT']
Length: 7, dtype: str

In [27]:
# Check benchmark columns first
print(benchmark.columns.tolist())
print(benchmark.head())

['date', 'index_name', 'close_value']
         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [28]:
benchmark["date"] = pd.to_datetime(benchmark["date"])
nifty100 = benchmark[benchmark["index_name"] == "NIFTY100"].copy()  # adjust exact string once confirmed
nifty100 = nifty100.sort_values("date")
nifty100["benchmark_return"] = nifty100["close_value"].pct_change()

alpha_beta_results = []
for code, group in nav_history.groupby("amfi_code"):
    merged = group.merge(nifty100[["date","benchmark_return"]], on="date", how="inner").dropna(
        subset=["daily_return","benchmark_return"])
    if len(merged) < 30:
        continue
    slope, intercept, r_value, p_value, std_err = stats.linregress(
        merged["benchmark_return"], merged["daily_return"])
    beta = slope
    alpha = intercept * 252
    alpha_beta_results.append({"amfi_code": code, "alpha": alpha, "beta": beta, "r_squared": r_value**2})

alpha_beta_df = pd.DataFrame(alpha_beta_results)
alpha_beta_df

    amfi_code     alpha      beta     r_squared
0      100016  0.037476 -0.058268  2.665033e-03
1      100025  0.042818  0.001158  1.461284e-05
2      100033  0.271954  0.005104  1.206652e-05
3      101206  0.213998  0.021086  3.480482e-04
4      101207  0.108971 -0.065289  1.064105e-03
5      101208  0.060861  0.000267  4.607624e-05
6      102885  0.170488 -0.019487  3.828503e-04
7      102886  0.028969 -0.042125  8.964295e-04
8      102887  0.162113  0.016683  1.861917e-04
9      118632  0.218294 -0.008354  5.791756e-05
10     118633  0.156438 -0.036639  1.138295e-03
11     118634  0.175007  0.103497  2.793007e-03
12     118635  0.151364 -0.001434  2.025341e-06
13     118636  0.050748  0.001257  1.651665e-05
14     119092  0.068995  0.009731  8.082638e-05
15     119093  0.082328  0.025883  5.692038e-04
16     119094  0.260767 -0.066265  1.936879e-03
17     119095  0.048016 -0.066951  1.185159e-03
18     119120  0.056209 -0.006414  4.342603e-04
19     119551  0.232010 -0.031751  8.869789e-04
20     119552  0.198686 -0.026159  5.850822e-04
21     119598  0.303370 -0.023196  1.414258e-04
22     119599  0.048824  0.062002  1.025921e-03
23     120503  0.177033 -0.040269  1.397445e-03
24     120504  0.211948  0.016232  2.121613e-04
25     120505  0.292636  0.000549  1.345534e-07
26     120506  0.162539  0.041896  1.257118e-03
27     120507  0.067462 -0.000444  1.343066e-04
28     120841  0.130429  0.036356  1.211371e-03
29     120842  0.078044  0.018057  1.691555e-04
30     120843  0.273305 -0.022830  3.430543e-04
31     120844  0.064557 -0.000401  1.012544e-04
32     125497  0.177298  0.048820  1.840179e-03
33     125498  0.119891  0.009054  4.043747e-05
34     148567  0.269838  0.023684  4.625437e-04
35     148568  0.208730 -0.026388  4.859265e-04
36     148569  0.282704  0.018134  1.748889e-04
37     149322  0.131732 -0.004050  1.322761e-05
38     149323  0.265986 -0.002523  3.357978e-06
39     149324  0.300579  0.011455  3.532991e-05

In [29]:
mdd_results = []
for code, group in nav_history.groupby("amfi_code"):
    group = group.sort_values("date")
    running_max = group["nav"].cummax()
    drawdown = group["nav"] / running_max - 1
    max_dd = drawdown.min()
    worst_idx = drawdown.idxmin()
    worst_date = group.loc[worst_idx, "date"]
    peak_date = group.loc[:worst_idx][group.loc[:worst_idx, "nav"] == running_max.loc[worst_idx]]["date"].iloc[0] if len(group.loc[:worst_idx]) > 0 else None
    mdd_results.append({"amfi_code": code, "max_drawdown": max_dd, "trough_date": worst_date})

mdd_df = pd.DataFrame(mdd_results)
mdd_df

    amfi_code  max_drawdown trough_date
0      100016     -0.247344  2022-09-15
1      100025     -0.043083  2023-07-28
2      100033     -0.162172  2022-05-12
3      101206     -0.112916  2023-07-05
4      101207     -0.354469  2026-05-11
5      101208     -0.001622  2023-09-12
6      102885     -0.108599  2022-03-29
7      102886     -0.280011  2026-04-27
8      102887     -0.215398  2022-07-04
9      118632     -0.174141  2024-07-19
10     118633     -0.186297  2024-02-29
11     118634     -0.233449  2026-02-20
12     118635     -0.116506  2022-06-09
13     118636     -0.083164  2024-02-09
14     119092     -0.144016  2025-02-07
15     119093     -0.217514  2023-05-22
16     119094     -0.209609  2022-08-11
17     119095     -0.516778  2026-05-11
18     119120     -0.043287  2025-04-01
19     119551     -0.150124  2024-02-05
20     119552     -0.118035  2024-09-02
21     119598     -0.287060  2025-05-14
22     119599     -0.525742  2025-10-28
23     120503     -0.138979  2023-11-09
24     120504     -0.125883  2023-05-30
25     120505     -0.181885  2025-01-23
26     120506     -0.198257  2023-08-14
27     120507     -0.000977  2025-10-20
28     120841     -0.175736  2025-02-14
29     120842     -0.240035  2024-10-17
30     120843     -0.129740  2022-04-13
31     120844     -0.001163  2024-04-30
32     125497     -0.152000  2025-01-01
33     125498     -0.211173  2025-09-12
34     148567     -0.112657  2023-10-20
35     148568     -0.152726  2024-01-24
36     148569     -0.163967  2023-10-20
37     149322     -0.148446  2022-02-04
38     149323     -0.172481  2022-10-24
39     149324     -0.311719  2025-01-03

In [30]:
scorecard = cagr_df[["amfi_code","scheme_name","cagr_3yr"]].merge(
    sharpe_df[["amfi_code","sharpe_ratio"]], on="amfi_code").merge(
    alpha_beta_df[["amfi_code","alpha"]], on="amfi_code").merge(
    fund_master[["amfi_code","expense_ratio_pct"]], on="amfi_code").merge(
    mdd_df[["amfi_code","max_drawdown"]], on="amfi_code")

def rank_to_score(series, ascending=False):
    ranks = series.rank(ascending=ascending, pct=True)
    return ranks * 100

scorecard["return_score"] = rank_to_score(scorecard["cagr_3yr"])
scorecard["sharpe_score"] = rank_to_score(scorecard["sharpe_ratio"])
scorecard["alpha_score"] = rank_to_score(scorecard["alpha"])
scorecard["expense_score"] = rank_to_score(scorecard["expense_ratio_pct"], ascending=True)  # lower is better
scorecard["dd_score"] = rank_to_score(scorecard["max_drawdown"], ascending=True)  # closer to 0 (less negative) is better

scorecard["overall_score"] = (
    0.30 * scorecard["return_score"] +
    0.25 * scorecard["sharpe_score"] +
    0.20 * scorecard["alpha_score"] +
    0.15 * scorecard["expense_score"] +
    0.10 * scorecard["dd_score"]
)

scorecard = scorecard.sort_values("overall_score", ascending=False)
scorecard.to_csv("../fund_scorecard.csv", index=False)
scorecard

,amfi_code,scheme_name,cagr_3yr,sharpe_ratio,alpha,expense_ratio_pct,max_drawdown,return_score,sharpe_score,alpha_score,expense_score,dd_score,overall_score
14,119092,Axis Bluechip Fund - Regular - Growth,0.005258,-0.131009,0.068995,1.64,-0.144016,90.0,75.0,75.0,98.75,65.0,82.0625
0,100016,HDFC Top 100 Fund - Regular Plan - Growth,0.012924,-0.321019,0.037476,1.55,-0.247344,87.5,85.0,97.5,80.00,17.5,80.7500
7,102886,UTI Mid Cap Fund - Regular - Growth,-0.007672,-0.294889,0.028969,1.51,-0.280011,92.5,82.5,100.0,61.25,15.0,79.0625
5,101208,ABSL Liquid Fund - Regular - Growth,0.063143,-4.650401,0.060861,0.79,-0.001622,77.5,100.0,82.5,27.50,95.0,78.3750
1,100025,HDFC Short Term Debt Fund - Regular - Growth,0.039155,-1.039941,0.042818,0.56,-0.043083,85.0,92.5,95.0,5.00,92.5,77.6250
17,119095,Axis Small Cap Fund - Regular - Growth,-0.117033,-0.151658,0.048016,1.38,-0.516778,100.0,80.0,92.5,42.50,5.0,75.3750
18,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,0.058390,-0.743099,0.056209,0.77,-0.043287,80.0,87.5,85.0,22.50,90.0,75.2500
13,118636,Nippon India Gilt Securities Fund - Regular - ...,0.040613,-0.850579,0.050748,0.55,-0.083164,82.5,90.0,87.5,2.50,87.5,73.8750
31,120844,Kotak Liquid Fund - Regular - Growth,0.066944,-4.000349,0.064557,0.60,-0.001163,75.0,97.5,80.0,7.50,97.5,73.7500
27,120507,ICICI Pru Liquid Fund - Regular - Growth,0.073925,-3.650184,0.067462,0.74,-0.000977,72.5,95.0,77.5,17.50,100.0,73.6250
4,101207,ABSL Small Cap Fund - Regular - Growth,-0.041515,0.052618,0.108971,1.53,-0.354469,97.5,67.5,67.5,71.25,7.5,71.0625
22,119599,SBI Small Cap Fund - Direct Plan - Growth,-0.013371,-0.136178,0.048824,0.72,-0.525742,95.0,77.5,90.0,13.75,2.5,68.1875
29,120842,Kotak Emerging Equity Fund - Regular - Growth,0.077542,-0.058167,0.078044,1.56,-0.240035,70.0,72.5,72.5,82.50,20.0,68.0000
28,120841,Kotak Bluechip Fund - Regular - Growth,0.172630,0.255117,0.130429,1.59,-0.175736,55.0,60.0,62.5,87.50,42.5,61.3750
37,149322,DSP Top 100 Equity Fund - Regular - Growth,0.180397,0.239663,0.131732,1.54,-0.148446,52.5,62.5,60.0,76.25,62.5,61.0625
11,118634,Nippon India Small Cap Fund - Regular - Growth,0.080060,0.292343,0.175007,1.53,-0.233449,67.5,57.5,45.0,71.25,22.5,56.5625
33,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,0.112425,0.134798,0.119891,0.78,-0.211173,65.0,65.0,65.0,25.00,30.0,55.5000
6,102885,UTI Nifty 50 Index Fund - Regular - Growth,0.196624,0.519797,0.170488,1.57,-0.108599,45.0,40.0,47.5,85.00,85.0,54.2500
23,120503,ICICI Pru Bluechip Fund - Regular - Growth,0.139750,0.516550,0.177033,1.42,-0.138979,62.5,42.5,42.5,50.00,67.5,52.1250
8,102887,UTI Flexi Cap Fund - Regular - Growth,0.255497,0.384637,0.162113,1.64,-0.215398,32.5,55.0,52.5,98.75,27.5,51.5625
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,0.147444,0.640673,0.208730,1.52,-0.152726,60.0,37.5,35.0,66.25,55.0,49.8125
12,118635,Nippon India ETF Nifty 50 BeES,0.200032,0.393188,0.151364,0.89,-0.116506,42.5,50.0,57.5,32.50,77.5,49.3750
15,119093,Axis Bluechip Fund - Direct - Growth,0.208116,-0.047073,0.082328,0.75,-0.217514,40.0,70.0,70.0,20.00,25.0,49.0000
26,120506,ICICI Pru Value Discovery Fund - Regular - Growth,0.184174,0.404615,0.162539,1.41,-0.198257,50.0,47.5,50.0,47.50,35.0,47.5000
32,125497,HDFC Top 100 Fund - Direct Plan - Growth,0.184299,0.506273,0.177298,0.92,-0.152000,47.5,45.0,40.0,35.00,57.5,44.5000
20,119552,SBI Bluechip Fund - Direct Plan - Growth,0.162634,0.648241,0.198686,0.66,-0.118035,57.5,35.0,37.5,10.00,75.0,42.5000
10,118633,Nippon India Large Cap Fund - Direct - Growth,0.210847,0.388829,0.156438,0.72,-0.186297,37.5,52.5,55.0,13.75,37.5,41.1875
3,101206,ABSL Frontline Equity Fund - Regular - Growth,0.289602,0.717409,0.213998,1.60,-0.112916,22.5,25.0,30.0,91.25,80.0,40.6875
38,149323,DSP Midcap Fund - Regular - Growth,0.268631,0.832885,0.265986,1.61,-0.172481,27.5,15.0,20.0,95.00,47.5,35.0000
9,118632,Nippon India Large Cap Fund - Regular - Growth,0.226466,0.758851,0.218294,1.51,-0.174141,35.0,20.0,27.5,61.25,45.0,34.6875
19,119551,SBI Bluechip Fund - Regular Plan - Growth,0.304486,0.860977,0.232010,1.54,-0.150124,15.0,12.5,25.0,76.25,60.0,30.0625
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,0.291714,0.919047,0.282704,1.60,-0.163967,20.0,7.5,10.0,91.25,50.0,28.5625
24,120504,ICICI Pru Bluechip Fund - Direct - Growth,0.324789,0.714682,0.211948,0.80,-0.125883,7.5,27.5,32.5,30.00,72.5,27.3750
39,149324,DSP Small Cap Fund - Regular - Growth,0.269935,0.714422,0.300579,1.52,-0.311719,25.0,30.0,5.0,66.25,10.0,26.9375
21,119598,SBI Small Cap Fund - Regular Plan - Growth,0.266631,0.711690,0.303370,1.43,-0.287060,30.0,32.5,2.5,52.50,12.5,26.7500
30,120843,Kotak Flexicap Fund - Regular - Growth,0.295751,0.965561,0.273305,1.45,-0.129740,17.5,5.0,12.5,55.00,70.0,24.2500
34,148567,Mirae Asset Large Cap Fund - Regular - Growth,0.339920,1.068224,0.269838,1.46,-0.112657,5.0,2.5,17.5,57.50,82.5,22.5000
2,100033,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,0.324340,0.808268,0.271954,1.38,-0.162172,10.0,17.5,15.0,42.50,52.5,22.0000
16,119094,Axis Midcap Fund - Regular - Growth,0.351025,0.730547,0.260767,1.38,-0.209609,2.5,22.5,22.5,42.50,32.5,20.5000
25,120505,ICICI Pru Midcap Fund - Regular - Growth,0.317692,0.883256,0.292636,1.36,-0.181885,12.5,10.0,7.5,37.50,40.0,17.3750

In [33]:
nifty100 = benchmark[benchmark["index_name"] == "NIFTY100"].copy()
nifty100 = nifty100.sort_values("date")
nifty100["benchmark_return"] = nifty100["close_value"].pct_change()
nifty100["cum_return"] = (1 + nifty100["benchmark_return"].fillna(0)).cumprod() - 1

nifty50 = benchmark[benchmark["index_name"] == "NIFTY50"].copy()
nifty50 = nifty50.sort_values("date")
nifty50["cum_return"] = (1 + nifty50["close_value"].pct_change().fillna(0)).cumprod() - 1

top5_codes = scorecard.head(5)["amfi_code"].tolist()

fig = go.Figure()
for code in top5_codes:
    fund_data = nav_history[nav_history["amfi_code"] == code].sort_values("date").tail(756)
    fund_data = fund_data.copy()
    fund_data["cum_return"] = (fund_data["nav"] / fund_data["nav"].iloc[0]) - 1
    name = fund_master[fund_master["amfi_code"]==code]["scheme_name"].values[0]
    fig.add_trace(go.Scatter(x=fund_data["date"], y=fund_data["cum_return"], name=name))

fig.add_trace(go.Scatter(x=nifty50["date"], y=nifty50["cum_return"], name="Nifty 50", line=dict(dash="dash")))
fig.add_trace(go.Scatter(x=nifty100["date"], y=nifty100["cum_return"], name="Nifty 100", line=dict(dash="dash")))
fig.update_layout(title="Top 5 Funds vs Nifty 50 & Nifty 100 (3yr Cumulative Return)")
fig.write_image(CHARTS + "10_benchmark_comparison.png", width=1400, height=700)
fig.show()

# Tracking error
for code in top5_codes:
    merged = nav_history[nav_history["amfi_code"]==code].merge(
        nifty100[["date","benchmark_return"]], on="date", how="inner").dropna(
        subset=["daily_return","benchmark_return"])
    te = (merged["daily_return"] - merged["benchmark_return"]).std() * np.sqrt(252)
    print(f"{code}: tracking error = {te:.4f}")

119092: tracking error = 0.1891
100016: tracking error = 0.1993
102886: tracking error = 0.2256
101208: tracking error = 0.1290
100025: tracking error = 0.1345

In [32]:
scorecard.to_csv("../fund_scorecard.csv", index=False)
alpha_beta_df.to_csv("../alpha_beta.csv", index=False)